### ISSUE TITLE
Synchronization of your contribution with espeak project on github

### ISSUE THREAD

**Issue by ghost** [puzzlet/espeak-korean#2]
Hello!
Espeak community seems to have decided to move form sourceforge to github.
Can you synchronize/recreate your project as a fork of https://github.com/espeak/espeak/ to be easier and more error resistant to merge in this new repository?
Thanks!

**Comment by ValdisVitolins** [comment]
We agreed with Reece Dunn, that to avoid confusion with original espeak, repository will be: https://github.com/espeak-ng/espeak-ng

**Comment by puzzlet** [comment]
Technically this project isn't a fork of eSpeak; just a collection of some data files for it. There's a link to eSpeak via `git submodule` though.

**Comment by ValdisVitolins** [comment]
So, is it espeak-ng now in better shape for Korean support, or is it your project?
They differ, but I don't know which one is newer/better. And if better is your project, we should merge it into main project.

**Comment by puzzlet** [comment]
@ValdisVitolins The data here is the older. It is no far different from [what had been included in eSpeak 1.46.24](http://sourceforge.net/p/espeak/discussion/538922/thread/52808d5d/). Over versions and versions the data [seem to have been modified](https://github.com/rhdunn/espeak/commits/master/dictsource/ko_rules) in the eSpeak repository. I'll have to look to catch up.
